### PR TITLE
Example fixes

### PR DESCRIPTION
**Pull request by hmueller01**
I am sorry, but I still have some fixes.
First I forgot to update the examples. This time I compiled with ESP8266 **and** ESP32.
I also changed the variable `ESP_WM_LITE_HTML_HEAD_CUSTOMS_STYLE` to `_CustomsHeadStyle` as this is no define ... (maybe in an earlier version you used a define for that).
Eventually I need to implement all this in the Async version ...

### CODE REVIEW

**Comment by hmueller01** [comment]
Please do not merge yet. I will include another commit (to better align this version with ESPAsync_WiFiManager_Lite)

**Comment by hmueller01** [comment]
Ok, it's done.

**Comment by khoih-prog** [comment]
Everything is OK. Merging now.

**Comment by khoih-prog** [comment]
Hi @hmueller01 

The merge is much easier and smoother everyday. Good job.

---

### Release v1.10.5

1. Using PROGMEM for strings in examples. Check [**Example fixes** #37](https://github.com/khoih-prog/ESP_WiFiManager_Lite/pull/37)
2. Improve `README.md` so that links can be used in other sites, such as `PIO`

**Pull request merged**
