### PR TITLE
Mobile scale

### PR DESCRIPTION
**Pull request by hmueller01**
set viewport scaling for mobile devices

### CODE REVIEW

**Comment by khoih-prog** [comment]
Hi @hmueller01 

Very good PR, as I don't use and have experience with mobile devices for Config-Portal

I'd really like this one and could you propagate to other WiFiManager-related libraries as well.
If you have no time, I'll do it.

Tested OK on iPhone.

Merging now.

Best Regards,

**Comment by hmueller01** [comment]
Yes, makes it easier to use on a mobile. This and the Captive Portal is really good!

Have you set 
`#define MANUAL_SSID_INPUT_ALLOWED true`
in your defines?

On my Android device I can not open the options (available SSIDs). They do not show up. It works perfect on my Mac with Chrome or the buildin Captive Portal browser. But not on the mobile. Does it work on your iPhone (I do not have one). I already played around with different ways of options `<option value='abc'>` (which is better HTML IMHO), instead of `<option>abc`. But it did not help. Setting the define to false works, but then of course without the possibility to manually enter a SSID ...

**Comment by khoih-prog** [comment]
> Have you set
> #define MANUAL_SSID_INPUT_ALLOWED true
> in your defines?

No. Just use default settings in example. I have to input PWD manually

---

### iPhone Screenshot

Screenshot 2023-01-15 at 1 38 43 PM

**Comment by hmueller01** [comment]
true is default. From examples define.h:
```
// To be able to manually input SSID, not from a scanned SSID lists
#define MANUAL_SSID_INPUT_ALLOWED           true
```
So yes, you use it.
Can you select a SSID from the list (by clicking on the blue down arrow)?
Do you have a chance to test it with an Android device? It should not work (or there is another problem on my side ...).
BTW: I use the latest Android from Google.

**Comment by khoih-prog** [comment]
> I have to input PWD manually

> Oh, I just read that you have to enter manually. So it sounds like it does not work on Apple ...

No. It's working OK on iPhone. Just `confusingly` said I entered **Config-Portal PWD manually**, but **Config-Portal SSID** is select from a list.

The Captive Portal is working on iPhone, thanks to your previous PS.

For AP SSID, we can select from the list or enter manually.

---

> Do you have a chance to test it with an Android device?

No time now. Will find an Android mobile device and see.

**Comment by hmueller01** [comment]
Maybe it would have been better to write this in a separate issue. Sorry for beginning the discussion here.

**Comment by khoih-prog** [comment]
OK on old SAMSUNG Android now. we still can select AP SSID from a list.

Android_CP

**Comment by hmueller01** [comment]
Ok, many thanks for testing it!
It's not working with the (internal) browser that automatically opens up after connecting with the ESP8266. But if I choose "Use this network anyway" (I do not know the exact words, as my phone is in German) and use Google Chrome afterwards I can select from the list. So it looks like the "internal" browser did not implement the list/option HTML code. I just tried on a second Motorola phone with Android 12. Same situation. But at least I now know what to do. Tx!

**Pull request merged**
