### PR TITLE
Captive portal

### PR DESCRIPTION
**Pull request by hmueller01**
added feature captive portal

### CODE REVIEW

**Comment by khoih-prog** [comment]
Sorry for the delay as I'm busy with something else new and more interesting.

Merged now.

**Comment by khoih-prog** [comment]
Hi @hmueller01 

The new [**ESP_WiFiManager_Lite releases v1.10.0**](https://github.com/khoih-prog/ESP_WiFiManager_Lite/releases/tag/v1.10.0) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/ESP_WiFiManager_Lite#contributions-and-thanks)

Best Regards,

---

### Release v1.10.0

1. Add Captive-Portal feature. Check [Captive portal #24](https://github.com/khoih-prog/ESP_WiFiManager_Lite/pull/24)
2. Add option to not `USE_LED_BUILTIN` for Config-Portal. Check [added switch to turn use of builtin LED off #20](https://github.com/khoih-prog/ESP_WiFiManager_Lite/pull/20)
3. Code clean-up

**Comment by hmueller01** [comment]
Hey @khoih-prog, thanks for merging! Just a small note. Why did you use version 1.10.0 here and 1.9.1 at [ESPAsync_WiFiManager_Lite](https://github.com/khoih-prog/ESPAsync_WiFiManager_Lite)? Shouldn't stay this the same?

**Comment by khoih-prog** [comment]
They are sync'ed @ `v1.10.1` now. Thanks for the note.

**Pull request merged**
